### ISSUE TITLE
Tags as field not facet?

### ISSUE THREAD

**Issue by drmikeuk** [whiskyechobravo/kerkoapp#14]
Hi,

I have too many tags in my library so these don't work as facets.
Thats OK as I can exclude with KERKOAPP_EXCLUDE_DEFAULT_FACETS and create new, simpler, facets based off sub-collections & configure with KERKOAPP_COLLECTION_FACETS.
Great!

But now my tags don't show up on the item page.
Is there any way round this?

Could I tweak the code to create a new **field**, not **facet**, in composer.py?
And if so how do I tweak the template to display this (ideally as simple text field eg "Keywords: aaa, bbb, ccc") ?

eg I think this works as I can now search on my tags 
if 'z_tags' not in exclude:
    self.add_field(
        FieldSpec(
            key='z_tags',
            field_type=self.secondary_id_field_type,
            scopes=['all'],
            extractor=extractors.TagsFacetExtractor(
                include_re=self.default_tag_include_re,
                exclude_re=self.default_tag_exclude_re
            )
        )
    )

**Comment by davidlesieur** [comment]
Hi, it looks like you're very close to have it done!

For the `field_type` parameter, I suggest that you use `field_type=STORED` instead of `self.secondary_id_field_type`. Tags are already searchable by default (through the `text_tags` field), so all you need is a stored field that you will be able to retrieve for display.

Once that is done, I think you'll be able to display your new field by adding something like the following in the `item.html.jinja2` template, perhaps right above the `field(_("Notes")` line:

        {{- field(_("Keywords"), item.z_tags|join(', ')|escape) if item.z_tags }}

More tweaking might be needed to sort the tags or to improve the formatting. And I might be forgetting stuff since the above is untested code 😉, but I hope it helps.

**Comment by davidlesieur** [comment]
Also, remove the `scopes` parameter. It's unneeded because the `text_tags` field will be used for search, not your new field.

**Comment by drmikeuk** [comment]
That works perfectly.
Thanks a lot!

**Comment by davidlesieur** [comment]
One last suggestion: add your new field in KerkoApp's `config.py` instead of altering Kerko's `composer.py`. It will make things easier should you want to upgrade Kerko in the future.
