### ISSUE TITLE
Document the MODULE_NAME variable

### ISSUE THREAD

**Issue by amv** [whiskyechobravo/kerkoapp#18]
This makes the container simply output the hello world message when running the current whiskyechobravo/kerkoapp docker image.

I was able to get docker to load the proper app by adding either one of these two lines in the .env file:

APP_MODULE=kerkoapp:app
MODULE_NAME=kerkoapp

But for some reason I also had to provide the following .env variables to get the server actually running:

FLASK_APP=kerkoapp.py
FLASK_ENV=development

Would be nice to have these either documented or fixed by default :)

**Comment by amv** [comment]
Ah it looks like the MODULE_NAME variable is actually present in the sample env file. I failed to miss it as I just built my env file from scratch and the variable was not documented as being mandatory.

**Comment by davidlesieur** [comment]
Right, `MODULE_NAME` is not mentioned in KerkoApp's documentation because it is used by Gunicorn, not by KerkoApp. Nevertheless, it probably ought to be mentioned in KerkoApp's Docker-related instructions since the container uses Gunicorn. I'll gladly take pull requests that improve the documentation and reduce hurdles for new users!
