### ISSUE TITLE
No items in zotero... since kerko shows files

### ISSUE THREAD

**Issue by ttannishh2** [whiskyechobravo/kerkoapp#35]
I had uploaded files on Zotero and ran Kerko. It worked great.

Now on deleting files and even after syncing kerko(using flask kerko sync), I am still getting those files. 

Am I missing something?

**Comment by davidlesieur** [comment]
By files, you mean file attachments? I have never observed cases where deleted attachments in Zotero were still showing up in Kerko after a sync. 

Is it possible that the sync is not actually completing? Or that file permissions have changed since the first sync, preventing Kerko from being able to remove the files?

Have you tried to clean everything with "flask kerko clean", then redoing "flask kerko sync"? Normally a clean would not be necessary, but with the info I have it's hard to tell what's happening.

**Comment by davidlesieur** [comment]
Perhaps the attachments are deleted locally in your Zotero library, but the change not yet synchronized on zotero.org? If that's the case, you would need to synchronize Zotero first, otherwise Kerko would still get the older version from zotero.org.

**Comment by ttannishh2** [comment]
So basically I uploaded 'case' files on Zotero, and kerko worked fine on it. 
Then I deleted them from Zotero, and uploaded a new set of 'case' files. Now, on kerko, it shows the past case files as well. 
A strange thing I noticed... on applying any facet, only the new files uploaded are being filtered, but when no filters are there,  kerko shows the old files as well.

**Comment by ttannishh2** [comment]
yes, bibliographic references.

mac M1

Also, I changed the library and got no error there.

**Comment by davidlesieur** [comment]
Not sure what you mean by "I changed the library and got no error there". Do you mean the issue is resolved?

**Comment by ttannishh2** [comment]
As in, I tried it on another library of another account and its working fine.

**Comment by davidlesieur** [comment]
Strange that you got this issue in the first place, but I'm glad it's resolved!
