### ISSUE TITLE
Custom front-end with Docker installation

### ISSUE THREAD

**Issue by nickpasiuk** [whiskyechobravo/kerkoapp#41]
Hello there! I came across this information in the documentation: the front-end of the application can be customized by partially or fully replacing the default templates, scripts, and stylesheets with custom ones. However, I am unsure about the location where I can include my own custom CSS when using the Docker installation of Demo. Thank you for any assistance you can provide!

**Comment by davidlesieur** [comment]
I have responded to #40 with some info on how to customize the front-end. I think a good location for your static resources should be a `static/` directory directly under the `kerkoapp/` directory. But then you will need to build your own Docker image, so that the files get copied into the container. That can be done with `make clean_image && make build`. I hope this helps!
